apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot
  template:
    metadata:
      labels:
        app: springboot
    spec:
      containers:
        - name: springboot
          image: gcr.io/pntabach-459816/springboot-app
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://aws-0-eu-north-1.pooler.supabase.com:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres.wrcyhszdmxtwvkfgqntz
            - name: SPRING_DATASOURCE_PASSWORD
              value: Admin12344*
---
apiVersion: v1
kind: Service
metadata:
  name: springboot-service
spec:
  type: LoadBalancer
  selector:
    app: springboot
  ports:
    - port: 80
      targetPort: 8080
